title: Steven Waterman
description: > # this means to ignore newlines until "baseurl:"
  Personal site for software developer Steven Waterman, developer of sharpshot.
#permalink: 'http://www.stevenwaterman.uk'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.stevenwaterman.uk" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Steven Waterman # add your name
author-img: steven-waterman.jpg # add your photo
about-author: I am a software developer, focusing on back-end development and data engineering. I'm working on a game called sharpshot, and a lot of what I talk about will be updates on the game's progress. # add description
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: motherlymuppet # add your Github handle
social-linkedin: steven-waterman # add your Linkedin handle
social-email: website@stevenwaterman.uk # add your Email address

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
#analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
